# Generated by Django 3.2.6 on 2021-11-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('image', models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name=' Изоражение')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('memory', models.CharField(max_length=255, verbose_name='Память')),
                ('ram', models.CharField(max_length=255, verbose_name='ОЗУ')),
                ('cpu', models.CharField(max_length=255, verbose_name='Процессор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name=' Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('image', models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name=' Изоражение')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('ram', models.CharField(max_length=255, verbose_name='ОЗУ')),
                ('video_card', models.CharField(max_length=255, verbose_name='Видео карта')),
                ('battery_life', models.CharField(max_length=255, verbose_name='Время работы от аккамулятора')),
                ('cpu', models.CharField(max_length=255, verbose_name='Процессор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name=' Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
